### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by luca-lunati** [fhnw-oopI2/fs20-l05-ab-LunatiL#1]
Ich hatte Probleme AB04 umzusetzen und habe diese vorerst übersprungen. Danach sah ich, dass der Test von AB06 ebenfalls die Methode traders() verwendet.
AB06 hatte ich also korrekt gelöst, der Test ist aber fehlgeschlagen, weil AB04 noch fehlerhaft war.
Ist diese Reihenfolge so gewollt bzw. kann es in zukünftigen Prüfungen auch vorkommen, dass mehrere Tests von einer Implementation einer Methode abhängig sind?

**Comment by fhnw-webec** [comment]
Danke für diese Beobachtung. Da haben Sie völlig recht, das ist problematisch. In einer Prüfung darf so etwas nicht vorkommen (und kommt auch nicht vor :-)).

Ich habe kurz Ihre Lösungen durchgesehen. Das sieht gut aus! Es gibt an ein, zwei Stellen Optimierungsmöglichkeiten. Ich werde das AB noch besprechen. Wahrscheinlich per Video.

Ich wünsche eine gute Woche und bleiben Sie gesund.
